// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Api.Data;

#nullable disable

namespace Portfolio.Api.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260901104108_SeedInitialProjects")]
    partial class SeedInitialProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "IT Project Management Simulation",
                            Description = "A simulated enterprise IT project covering the planning and delivery of an employee self-service portal. The project demonstrates end-to-end project management across initiation, planning, technical design, Agile delivery, testing, deployment, transition and closure, supported by practical governance, quality, risk, stakeholder and delivery artifacts.",
                            IsFeatured = true,
                            Role = "Technical Project Manager / Scrum Master",
                            Status = "In Progress",
                            Summary = "End-to-end planning and delivery of an employee self-service portal using structured project governance, Agile practices, cross-functional coordination and delivery controls.",
                            Title = "PeopleFirst Employee Self-Service Portal"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Full-Stack Web Development",
                            Description = "A full-stack portfolio application built using React, TypeScript, ASP.NET Core, Entity Framework Core and SQL Server. The project applies iterative delivery, modular architecture, source control, accessibility practices, testing and release management while providing a professional platform for demonstrating IT project-management experience.",
                            IsFeatured = false,
                            Role = "Technical Project Manager / Developer",
                            Status = "In Progress",
                            Summary = "Design and development of a modular, accessible portfolio platform that demonstrates IT project-management capability through projects, case studies and practical delivery artifacts.",
                            Title = "IT Project Management Portfolio Platform"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
